name: CI/CD Pipeline for Student Portal

on:
  push:
    branches:
      - main  # Trigger this on push to main branch
  pull_request:
    branches:
      - main  # Trigger this on pull request to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

   

    # Log into Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Backend Docker Image
    - name: Build and Push Backend Docker Image
      run: |
        docker build -t prudhvee001/studentapp-backend:${{ github.sha }} -f backend/Dockerfile .
        docker push prudhvee001/studentapp-backend:${{ github.sha }}

    # Build and Push Frontend Docker Image
    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t prudhvee001/studentapp-frontend:${{ github.sha }} -f frontend/Dockerfile .
        docker push prudhvee001/studentapp-frontend:${{ github.sha }}

    # Set up kubectl to interact with the EKS cluster
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubectl-version: 'latest'

    # Deploy to EKS cluster
    - name: Deploy to EKS
      run: |
        aws eks --region us-east-1 update-kubeconfig --name student-portal-eks-cluster
        kubectl apply -f kubernetes/
