name: CI/CD Pipeline for Student Portal

on:
  push:
    branches:
      - main  # Trigger this on push to main branch
  pull_request:
    branches:
      - main  # Trigger this on pull request to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: List files in the repository for debugging
    - name: List files in the repository
      run: ls -la

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 4: Log into Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and Push Backend Docker Image
    - name: Build and Push Backend Docker Image
      run: |
        echo "Building backend Docker image..."
        docker build -t prudhvee001/studentapp-backend:${{ github.sha }} -f backend/Dockerfile .
        docker push prudhvee001/studentapp-backend:${{ github.sha }}

    # Step 6: Build and Push Frontend Docker Image
    - name: Build and Push Frontend Docker Image
      run: |
        echo "Building frontend Docker image..."
        docker build -t prudhvee001/studentapp-frontend:${{ github.sha }} -f frontend/Dockerfile .
        docker push prudhvee001/studentapp-frontend:${{ github.sha }}

    # Step 7: Set up kubectl to interact with the EKS cluster
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubectl-version: 'latest'

    # Step 8: Deploy to EKS cluster
    - name: Deploy to EKS
      run: |
        echo "Configuring EKS cluster..."
        aws eks --region us-east-1 update-kubeconfig --name student-portal-eks-cluster
        echo "Deploying backend and frontend services to EKS..."
        kubectl apply -f kubernetes/

    # Optional Step: Clean up unused Docker images (save space)
    - name: Clean up unused Docker images
      run: |
        docker system prune -f
